fail_on_severity: 'critical'

# https://github.com/cncf/foundation/blob/main/allowed-third-party-license-policy.md
allow-licenses:
- 'Apache-2.0'
- 'BSD-2-Clause'
- 'BSD-2-Clause-FreeBSD'
- 'BSD-3-Clause'
- 'ISC'
- 'MIT'
- 'PostgreSQL'
- 'Python-2.0'
- 'X11'
- 'Zlib'

allow-dependencies-licenses:
# this action is GPL-3 but it is only used in CI
# https://github.com/actions/dependency-review-action/issues/530#issuecomment-1638291806
- pkg:githubactions/vladopajic/go-test-coverage
# this package is MPL-2.0 and has a CNCF exception
# https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2022-04-12.json
- pkg:golang/github.com/go-sql-driver/mysql
# this package is MPL-2.0 and has a CNCF exception
# https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2022-04-12.json
- pkg:golang/github.com/hashicorp/go-version
# this package is MPL-2.0 and has a CNCF exception
# https://github.com/cncf/foundation/blob/main/license-exceptions/cncf-exceptions-2022-04-12.json
- pkg:golang/github.com/hashicorp/golang-lru
# this package is CC0-1.0 and is only used in test asserts
- pkg:golang/github.com/zeebo/assert
