site_name: 'Lagoon CLI'
site_url: https://uselagoon.github.io/lagoon-cli/
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'
  favicon: lagoon-cli-logo.png
  icon:
    logo: fontawesome/solid/terminal
extra:
  analytics:
    provider: google
    property: G-W1SJFEVFDB
markdown_extensions:
  - codehilite
  - admonition
  - attr_list
  - toc:
      permalink: "#"
      baselevel: 2
      separator: "_"
pages:
  - Getting Started: index.md
  - Configuration: config.md
  - Commands: commands/lagoon.md
