version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/uselagoon/lagoon-cli
    steps:
      - checkout
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: run tests
          command: make test
  deploy:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/uselagoon/lagoon-cli
    steps:
      - checkout
      - run: # test what branch we're on.
          name: "What branch am I on?"
          command: echo ${CIRCLE_TAG}
      - run:
          name: run build
          command: |
            make deps
            make build
      - run:
          name: compile
          command: |
            make VERSION=${CIRCLE_TAG} build-linux
            make VERSION=${CIRCLE_TAG} build-darwin
      - run:
          name: "Publish Release on GitHub"
          command: |
            GO111MODULE=auto go get github.com/tcnksm/ghr
            BODY=$(cat builds/release_template.md | sed 's@CIRCLE_TAG@'"${CIRCLE_TAG}"'@g')
            rm ./builds/README.md ./builds/release_template.md
            for BUILD in $(ls builds); do tar --transform="flags=r;s|${BUILD}|lagoon|" -czf builds/${BUILD}.tar.gz -C builds ${BUILD}; done
            ghr -n "Lagoon CLI v${CIRCLE_TAG}" -b "${BODY}" -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -delete ${CIRCLE_TAG} ./builds/
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              # only: /.*/
              ignore: gh-pages
            tags:
              only: /^\d+\.\d+\.\d+$/
      - deploy:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^\d+\.\d+\.\d+$/
