name: Release CLI

on:
  push:
    tags:
      v*

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: "0"

    - name: Install go1.13.7
      run: |
        #go
        sudo rm -rf /usr/local/go
        curl -sLo /tmp/go1.13.7.linux-amd64.tar.gz https://dl.google.com/go/go1.13.7.linux-amd64.tar.gz
        sudo tar -C /usr/local -xzf /tmp/go1.13.7.linux-amd64.tar.gz

    - name: Build CLI
      run: |
        make deps
        make build

    - name: Compile CLI
      run: |
        make VERSION=${GITHUB_REF##*/} build-linux
        make VERSION=${GITHUB_REF##*/} build-darwin
        # create the archived versions and remove anything not required for the release
        rm ./builds/README.md ./builds/release_template.md
        for BUILD in $(ls builds); do tar --transform="flags=r;s|${BUILD}|lagoon|" -czf builds/${BUILD}.tar.gz -C builds ${BUILD}; done

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          builds/*

    - name: Deploy Docs
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-pages
        folder: docs